### ISSUE TITLE
Can't change settings `select list` in spotify

### ISSUE THREAD

**Issue by hmanhng** [MichaelPachec0/spicetify-nix#10]
**Describe the bug**
When I click on list settings like change language,... just blink and exit, nothing happens

**My config**
``` nix
{
  inputs,
  inputs',
  pkgs,
  ...
}: {
  imports = [inputs.spicetify-nix.homeManagerModule];
  # themable spotify
  programs.spicetify = let
    spicePkgs = inputs'.spicetify-nix.packages.default;
  in {
    enable = true;
    injectCss = true;
    replaceColors = true;
    overwriteAssets = true;
    sidebarConfig = true;
    enabledCustomApps = with spicePkgs.apps; [lyrics-plus new-releases];
    theme = spicePkgs.themes.text;
    colorScheme = "rosepinemoon";
    enabledExtensions = with spicePkgs.extensions; [
      hidePodcasts
      shuffle
      adblock
      playlistIcons
      lastfm
      genre
      historyShortcut
      bookmark
      fullAlbumDate
      groupSession
      popupLyrics
    ];
  };
}
```

**Screenshots**
https://github.com/MichaelPachec0/spicetify-nix/assets/64454245/a82684c3-e8c6-4a0a-8dcf-7368ba37398c

**Desktop (please complete the following information):**
 - OS/distro: Nixos
 - Desktop environment/window manager: Hyprland
 - nixpkgs version for my home configuration: unstable
 - nixpkgs version for my import of spicetify nix: same as above

**Comment by MichaelPachec0** [comment]
For what i understand this is not an issue with this repo but an issue with text theme itself. There is a pr that will fix a couple issues with the theme (see spicetify/spicetify-themes#1012), if they are not fixed when this is merged it might make sense to raise an issue there.

**Comment by hmanhng** [comment]
I tried with other themes other than `text` and it still happens, is it a problem with `wm` or `wayland(hyprland)` ?

**Comment by MichaelPachec0** [comment]
> I tried with other themes other than `text` and it still happens, is it a problem with `wm` or `wayland(hyprland)`

I take it you are opening spotify in native (wayland) mode? It seems that is the issue or at least contributes to it. This happens even with vanilla spotify (with no theme change aka using the default theme). ~~This seems to be an issue with spotifywm which does not capture spotify's child windows(?) since~~ Starting spotify in xwayland mode (i.e `WAYLAND_DISPLAY="" spotify` ) works ~~and spotifywm does find the windows created by spotify~~.

That being said this all based on the small amount of time I have worked on trying to repro and debug the issue. ~~AFAICT this only happens when youre using spotify (wayland) + tiling wm~~.


EDIT: further research led me to this flathub/com.spotify.Client#183 which means it's a Spotify Wayland issue not a nix, spicetify or spotifywm issue.

**Comment by hmanhng** [comment]
Thanks for your support
